title: "C++23入門"
summary: "C++23への入門書"
topics: ["cpp"]
published: false
price: 0
chapters:
  - intro
  - setup
  - declaration
  - function
  - variable
  - expression-and-statement
  - integer-type
  - output
  - preprocessing-directive
  - branch
  - assignment
  - loop
  - multiple-files
  - translation
  - fundamental-types
  - logical-operators
  - const
  - class
  - default-initialization
  - access-control
  - type-and-function
  - reference-and-pointer
  - object-parameter
  - inheritance
